spring:
  application:
    name: Restro Application
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
